name: Continuous Integration
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'README.md'
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: dotnet build
      run: dotnet build --configuration 'Release'
    - name: dotnet test
      run: dotnet test --configuration 'Release'
