name: Deployment
on:
  push:
    branches: [ master ]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: publish
        run: dotnet publish --configuration Release
    - uses: maxheld83/ghpages@master
      name: gh-pages publish
      env:
        BUILD_DIR: dotnet-blazor-games\bin\Release\net5.0\publish\wwwroot
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}